//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Dynamics.AX.Framework.DocumentRouting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Dynamics.AX.Framework.DocumentRouting.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure AD Uri.
        /// </summary>
        public static string AADInstanceUriLabel {
            get {
                return ResourceManager.GetString("AADInstanceUriLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The agent version is different from the server platform version {0}..
        /// </summary>
        public static string AgentVersionIsDifferent {
            get {
                return ResourceManager.GetString("AgentVersionIsDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application ID.
        /// </summary>
        public static string ApplicationIDLabel {
            get {
                return ResourceManager.GetString("ApplicationIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access was denied. Ensure you are using the correct Email and Password. Click &apos;Sign In&apos; to try again..
        /// </summary>
        public static string AuthAccessDenied {
            get {
                return ResourceManager.GetString("AuthAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In Error.
        /// </summary>
        public static string AuthErrorDialogCaption {
            get {
                return ResourceManager.GetString("AuthErrorDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication cancelled. Click &apos;Sign In&apos; to try again..
        /// </summary>
        public static string AuthUserCancelled {
            get {
                return ResourceManager.GetString("AuthUserCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic unregistering disconnected printers.
        /// </summary>
        public static string AutoUnregisterDisconnectedPrintersLabel {
            get {
                return ResourceManager.GetString("AutoUnregisterDisconnectedPrintersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure AD Tenant.
        /// </summary>
        public static string AzureADTenantLabel {
            get {
                return ResourceManager.GetString("AzureADTenantLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Client ID.
        /// </summary>
        public static string AzureClientIDLabel {
            get {
                return ResourceManager.GetString("AzureClientIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonLabel {
            get {
                return ResourceManager.GetString("CancelButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for next document.
        /// </summary>
        public static string CheckingForNextDocument {
            get {
                return ResourceManager.GetString("CheckingForNextDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date / Time.
        /// </summary>
        public static string ColumnDateTimeLabel {
            get {
                return ResourceManager.GetString("ColumnDateTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string ColumnIdLabel {
            get {
                return ResourceManager.GetString("ColumnIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string ColumnLogDetailsLabel {
            get {
                return ResourceManager.GetString("ColumnLogDetailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string ColumnLogKeywordsLabel {
            get {
                return ResourceManager.GetString("ColumnLogKeywordsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string ColumnLogLevelLabel {
            get {
                return ResourceManager.GetString("ColumnLogLevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string ColumnLogMessageLabel {
            get {
                return ResourceManager.GetString("ColumnLogMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcode.
        /// </summary>
        public static string ColumnLogOpcodeLabel {
            get {
                return ResourceManager.GetString("ColumnLogOpcodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string ColumnLogTaskLabel {
            get {
                return ResourceManager.GetString("ColumnLogTaskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and Time.
        /// </summary>
        public static string ColumnLogTimeLabel {
            get {
                return ResourceManager.GetString("ColumnLogTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ColumnNameLabel {
            get {
                return ResourceManager.GetString("ColumnNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer.
        /// </summary>
        public static string ColumnPrinterLabel {
            get {
                return ResourceManager.GetString("ColumnPrinterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer name.
        /// </summary>
        public static string ColumnPrinterNameLabel {
            get {
                return ResourceManager.GetString("ColumnPrinterNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer path.
        /// </summary>
        public static string ColumnPrinterPathLabel {
            get {
                return ResourceManager.GetString("ColumnPrinterPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string ColumnSelectedLabel {
            get {
                return ResourceManager.GetString("ColumnSelectedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string ColumnSizeLabel {
            get {
                return ResourceManager.GetString("ColumnSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ColumnStatusLabel {
            get {
                return ResourceManager.GetString("ColumnStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        public static string DateTimeColumn {
            get {
                return ResourceManager.GetString("DateTimeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Routing Agent {0}.
        /// </summary>
        public static string DocumentRoutingAgentTask {
            get {
                return ResourceManager.GetString("DocumentRoutingAgentTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Routing Agent.
        /// </summary>
        public static string DocumentRoutingAgentTitle {
            get {
                return ResourceManager.GetString("DocumentRoutingAgentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Routing authentication {0}.
        /// </summary>
        public static string DocumentRoutingAuthenticationTask {
            get {
                return ResourceManager.GetString("DocumentRoutingAuthenticationTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Routing Printers page {0}.
        /// </summary>
        public static string DocumentRoutingPrintersPageTask {
            get {
                return ResourceManager.GetString("DocumentRoutingPrintersPageTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not running. It can be started from the Windows Services Administrative tool..
        /// </summary>
        public static string DocumentRoutingServiceNotRunning {
            get {
                return ResourceManager.GetString("DocumentRoutingServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Routing Settings page {0}.
        /// </summary>
        public static string DocumentRoutingSettingsPageTask {
            get {
                return ResourceManager.GetString("DocumentRoutingSettingsPageTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamics 365 URL.
        /// </summary>
        public static string DynamicsAXUrlLabel {
            get {
                return ResourceManager.GetString("DynamicsAXUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable logging view in application.
        /// </summary>
        public static string EnableInAppLoggingViewCheckboxLabel {
            get {
                return ResourceManager.GetString("EnableInAppLoggingViewCheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        public static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel:.
        /// </summary>
        public static string EventChannelsLabel {
            get {
                return ResourceManager.GetString("EventChannelsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string EventLogsLabel {
            get {
                return ResourceManager.GetString("EventLogsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last {0} day(s).
        /// </summary>
        public static string EventLogsTimeSpanItemLabel {
            get {
                return ResourceManager.GetString("EventLogsTimeSpanItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitLabel {
            get {
                return ResourceManager.GetString("ExitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string FolderLabelLabel {
            get {
                return ResourceManager.GetString("FolderLabelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string InformationCaption {
            get {
                return ResourceManager.GetString("InformationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking started: {0:hh:mm:ss}.
        /// </summary>
        public static string LastCheckedFormatString {
            get {
                return ResourceManager.GetString("LastCheckedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged:.
        /// </summary>
        public static string LoggedDaysCountLabel {
            get {
                return ResourceManager.GetString("LoggedDaysCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords:.
        /// </summary>
        public static string LogKeywordsFilterLabel {
            get {
                return ResourceManager.GetString("LogKeywordsFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        public static string LogLevelFilterLabel {
            get {
                return ResourceManager.GetString("LogLevelFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no activated printers found..
        /// </summary>
        public static string NoActivePrinters {
            get {
                return ResourceManager.GetString("NoActivePrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoLabel {
            get {
                return ResourceManager.GetString("NoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not signed in.
        /// </summary>
        public static string NotSignedIn {
            get {
                return ResourceManager.GetString("NotSignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The active user does not have write access to the selected folder..
        /// </summary>
        public static string NoWriteAccessError {
            get {
                return ResourceManager.GetString("NoWriteAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OKButtonLabel {
            get {
                return ResourceManager.GetString("OKButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse ....
        /// </summary>
        public static string PdfTargetFolderBrowseButtonLabel {
            get {
                return ResourceManager.GetString("PdfTargetFolderBrowseButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target folder for PDF files does not exist..
        /// </summary>
        public static string PdfTargetFolderDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("PdfTargetFolderDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the target folder for PDF files.
        /// </summary>
        public static string PdfTargetFolderGroupLabel {
            get {
                return ResourceManager.GetString("PdfTargetFolderGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target folder for PDF output is required when running as a Windows Service..
        /// </summary>
        public static string PdfTargetFolderRequiredError {
            get {
                return ResourceManager.GetString("PdfTargetFolderRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string PrinterInstalledLabel {
            get {
                return ResourceManager.GetString("PrinterInstalledLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer path must not be empty..
        /// </summary>
        public static string PrinterPathEmptyError {
            get {
                return ResourceManager.GetString("PrinterPathEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printers.
        /// </summary>
        public static string PrintersLabel {
            get {
                return ResourceManager.GetString("PrintersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document routing agent is currently checking for new or printing, would you like to wait?.
        /// </summary>
        public static string QuestionBeforeClosing {
            get {
                return ResourceManager.GetString("QuestionBeforeClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string QuestionCaption {
            get {
                return ResourceManager.GetString("QuestionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect URL.
        /// </summary>
        public static string RedirectUriLabel {
            get {
                return ResourceManager.GetString("RedirectUriLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This previously registered printer is not in the list of installed printers on the current computer..
        /// </summary>
        public static string RegistedNotInstalledToolTip {
            get {
                return ResourceManager.GetString("RegistedNotInstalledToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Unable to register printers..
        /// </summary>
        public static string RegisterPrintersError {
            get {
                return ResourceManager.GetString("RegisterPrintersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing the next document.
        /// </summary>
        public static string RoutingNextDocument {
            get {
                return ResourceManager.GetString("RoutingNextDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as Windows Service.
        /// </summary>
        public static string RunAsWindowsServiceCheckboxLabel {
            get {
                return ResourceManager.GetString("RunAsWindowsServiceCheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents being routed via Microsoft Dynamics 365 for Finance and Operations: Document Routing Service.
        /// </summary>
        public static string RunAsWindowsServiceStatusBarMessage {
            get {
                return ResourceManager.GetString("RunAsWindowsServiceStatusBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected log details:.
        /// </summary>
        public static string SelectedLogDetailsLabel {
            get {
                return ResourceManager.GetString("SelectedLogDetailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed in.
        /// </summary>
        public static string SignedIn {
            get {
                return ResourceManager.GetString("SignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in.
        /// </summary>
        public static string SigningIn {
            get {
                return ResourceManager.GetString("SigningIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignInLabel {
            get {
                return ResourceManager.GetString("SignInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOutLabel {
            get {
                return ResourceManager.GetString("SignOutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string StringConcatenationFormatString {
            get {
                return ResourceManager.GetString("StringConcatenationFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string TaskStart {
            get {
                return ResourceManager.GetString("TaskStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string TaskStop {
            get {
                return ResourceManager.GetString("TaskStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to sign in. Please update the settings..
        /// </summary>
        public static string UnableToSignIn {
            get {
                return ResourceManager.GetString("UnableToSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent could not connect to Microsoft Dynamics 365 for Finance and Operations. Agent version check failed. .
        /// </summary>
        public static string VersionCheckFailed {
            get {
                return ResourceManager.GetString("VersionCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for next document ....
        /// </summary>
        public static string WaitingForNextDocument {
            get {
                return ResourceManager.GetString("WaitingForNextDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document routing agent is busy and will be closed after current work is completed..
        /// </summary>
        public static string WindowIsWaitingToClose {
            get {
                return ResourceManager.GetString("WindowIsWaitingToClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesLabel {
            get {
                return ResourceManager.GetString("YesLabel", resourceCulture);
            }
        }
    }
}
