//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Dynamics.AX.Framework.DocumentRouting.Runtime {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Dynamics.AX.Framework.DocumentRouting.Runtime.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding the status task {0}..
        /// </summary>
        internal static string AddStatusMessage {
            get {
                return ResourceManager.GetString("AddStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adobe Acrobat Reader DC is not installed..
        /// </summary>
        internal static string AdobeAcrobatNotInstalled {
            get {
                return ResourceManager.GetString("AdobeAcrobatNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An application exception occurred in method {0}..
        /// </summary>
        internal static string ApplicationExceptionInMethod {
            get {
                return ResourceManager.GetString("ApplicationExceptionInMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} : {1}.
        /// </summary>
        internal static string ArgumentException {
            get {
                return ResourceManager.GetString("ArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the document contract from blob storage task start..
        /// </summary>
        internal static string DeleteDocumentContractFromBlobStorageTaskStart {
            get {
                return ResourceManager.GetString("DeleteDocumentContractFromBlobStorageTaskStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the document contract from blob storage task stop..
        /// </summary>
        internal static string DeleteDocumentContractFromBlobStorageTaskStop {
            get {
                return ResourceManager.GetString("DeleteDocumentContractFromBlobStorageTaskStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Routing authenticate {0}.
        /// </summary>
        internal static string DocumentRoutingAuthenticateTask {
            get {
                return ResourceManager.GetString("DocumentRoutingAuthenticateTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Routing: route document {0}.
        /// </summary>
        internal static string DocumentRoutingDocumentRouteTask {
            get {
                return ResourceManager.GetString("DocumentRoutingDocumentRouteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download document contract from blob storage task start..
        /// </summary>
        internal static string DownloadDocumentContractFromBlobStorageTaskStart {
            get {
                return ResourceManager.GetString("DownloadDocumentContractFromBlobStorageTaskStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download document contract from blob storage task stop..
        /// </summary>
        internal static string DownloadDocumentContractFromBlobStorageTaskStop {
            get {
                return ResourceManager.GetString("DownloadDocumentContractFromBlobStorageTaskStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happened in Stopping the Service.
        /// </summary>
        internal static string ErrorStopping {
            get {
                return ResourceManager.GetString("ErrorStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: {0}.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} on {1}.
        /// </summary>
        internal static string FriendlyPrinterNameFormat {
            get {
                return ResourceManager.GetString("FriendlyPrinterNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer Name {0} is not valid..
        /// </summary>
        internal static string InvalidPrinter {
            get {
                return ResourceManager.GetString("InvalidPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Print to PDF.
        /// </summary>
        internal static string MicrosoftPrintToPDFPrinterName {
            get {
                return ResourceManager.GetString("MicrosoftPrintToPDFPrinterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft XPS Document Writer.
        /// </summary>
        internal static string MicrosoftXpsDocumentWriterPrinterName {
            get {
                return ResourceManager.GetString("MicrosoftXpsDocumentWriterPrinterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentContract cannot be null or empty..
        /// </summary>
        internal static string NoDocumentContract {
            get {
                return ResourceManager.GetString("NoDocumentContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image produced..
        /// </summary>
        internal static string NoEmfImage {
            get {
                return ResourceManager.GetString("NoEmfImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no metafiles to send to the printer..
        /// </summary>
        internal static string NoMetafilesToPrint {
            get {
                return ResourceManager.GetString("NoMetafilesToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageSettings object sent to printer cannot be null or empty..
        /// </summary>
        internal static string NoPageSettings {
            get {
                return ResourceManager.GetString("NoPageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page sizes cannot be empty..
        /// </summary>
        internal static string NoPageSizes {
            get {
                return ResourceManager.GetString("NoPageSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Printer name supplied..
        /// </summary>
        internal static string NoPrinterName {
            get {
                return ResourceManager.GetString("NoPrinterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        internal static string NotAvailableMessage {
            get {
                return ResourceManager.GetString("NotAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageSettings format is not correct.
        /// </summary>
        internal static string PageSettingsFormatException {
            get {
                return ResourceManager.GetString("PageSettingsFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageSettingsRoot cannot be null..
        /// </summary>
        internal static string PageSettingsNotNull {
            get {
                return ResourceManager.GetString("PageSettingsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total of the page sizes provided, {0}, does not match the byte size of the report: {1}.
        /// </summary>
        internal static string PageSizesProvidedDoNotMatchSizeOfReport {
            get {
                return ResourceManager.GetString("PageSizesProvidedDoNotMatchSizeOfReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; must not be null or empty..
        /// </summary>
        internal static string ParameterMustNotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ParameterMustNotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid point structure for drawing image..
        /// </summary>
        internal static string PointNotSpecified {
            get {
                return ResourceManager.GetString("PointNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer is not available: {0}..
        /// </summary>
        internal static string PrinterIsNotAvailable {
            get {
                return ResourceManager.GetString("PrinterIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageSettings.PrinterName of parameter {0} must not be null..
        /// </summary>
        internal static string PrinterNameMustNotBeNull {
            get {
                return ResourceManager.GetString("PrinterNameMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of installed printers does not contain {0}..
        /// </summary>
        internal static string PrinterNotInInstalledPrintersList {
            get {
                return ResourceManager.GetString("PrinterNotInInstalledPrintersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of installed printers does not contain {0}. Retrying....
        /// </summary>
        internal static string PrinterNotInInstalledPrintersListRetry {
            get {
                return ResourceManager.GetString("PrinterNotInInstalledPrintersListRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageSettings of parameter {0} must not be null..
        /// </summary>
        internal static string PrinterSettingsMustNotBeNull {
            get {
                return ResourceManager.GetString("PrinterSettingsMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report failed to be sent to the printer..
        /// </summary>
        internal static string PrintFailureMessage {
            get {
                return ResourceManager.GetString("PrintFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing document {0}..
        /// </summary>
        internal static string PrintingDocument {
            get {
                return ResourceManager.GetString("PrintingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing document {0} failed..
        /// </summary>
        internal static string PrintingDocumentFailed {
            get {
                return ResourceManager.GetString("PrintingDocumentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing document {0} succeeded..
        /// </summary>
        internal static string PrintingDocumentSucceeded {
            get {
                return ResourceManager.GetString("PrintingDocumentSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report was successfully sent to the printer..
        /// </summary>
        internal static string PrintSuccessMessage {
            get {
                return ResourceManager.GetString("PrintSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process page settings tast start..
        /// </summary>
        internal static string ProcessPageSettingsTaskStart {
            get {
                return ResourceManager.GetString("ProcessPageSettingsTaskStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process page settings tast stop..
        /// </summary>
        internal static string ProcessPageSettingsTaskStop {
            get {
                return ResourceManager.GetString("ProcessPageSettingsTaskStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expected size of the file to be printed is {0} bytes, but the actual size is {1} bytes..
        /// </summary>
        internal static string ReportPageSizesInvalid {
            get {
                return ResourceManager.GetString("ReportPageSizesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send document contract to printer ask {0}.
        /// </summary>
        internal static string SendDocumentContractToPrinterTask {
            get {
                return ResourceManager.GetString("SendDocumentContractToPrinterTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Metafile page to printer task start..
        /// </summary>
        internal static string SendMetafilePageToPrinterTaskStart {
            get {
                return ResourceManager.GetString("SendMetafilePageToPrinterTaskStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Metafile page to printer task stop..
        /// </summary>
        internal static string SendMetafilePageToPrinterTaskStop {
            get {
                return ResourceManager.GetString("SendMetafilePageToPrinterTaskStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send metafile document to printer task start..
        /// </summary>
        internal static string SendMetafileToPrinterTaskStart {
            get {
                return ResourceManager.GetString("SendMetafileToPrinterTaskStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send metafile document to printer task stop..
        /// </summary>
        internal static string SendMetafileToPrinterTaskStop {
            get {
                return ResourceManager.GetString("SendMetafileToPrinterTaskStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send To OneNote.
        /// </summary>
        internal static string SendToOneNotePrinterName {
            get {
                return ResourceManager.GetString("SendToOneNotePrinterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Zebra printer task start..
        /// </summary>
        internal static string SendToZebraPrinterTaskStart {
            get {
                return ResourceManager.GetString("SendToZebraPrinterTaskStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Zebra printer task stop..
        /// </summary>
        internal static string SendToZebraPrinterTaskStop {
            get {
                return ResourceManager.GetString("SendToZebraPrinterTaskStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied SizeF object has a width or height that is 0.0f..
        /// </summary>
        internal static string SizeFDivideByZero {
            get {
                return ResourceManager.GetString("SizeFDivideByZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split byte array into Metafile pages task start..
        /// </summary>
        internal static string SplitIntoMetafilePagesTaskStart {
            get {
                return ResourceManager.GetString("SplitIntoMetafilePagesTaskStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split byte array into Metafile pages task stop..
        /// </summary>
        internal static string SplitIntoMetafilePagesTaskStop {
            get {
                return ResourceManager.GetString("SplitIntoMetafilePagesTaskStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string TaskStart {
            get {
                return ResourceManager.GetString("TaskStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task {0} Start.
        /// </summary>
        internal static string TaskStartFormatString {
            get {
                return ResourceManager.GetString("TaskStartFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string TaskStop {
            get {
                return ResourceManager.GetString("TaskStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task {0} Stop.
        /// </summary>
        internal static string TaskStopFormatString {
            get {
                return ResourceManager.GetString("TaskStopFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring the page settings for to printer specific page settings task start..
        /// </summary>
        internal static string TransferPageSettingsTastStart {
            get {
                return ResourceManager.GetString("TransferPageSettingsTastStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring the page settings for to printer specific page settings task stop..
        /// </summary>
        internal static string TransferPageSettingsTastStop {
            get {
                return ResourceManager.GetString("TransferPageSettingsTastStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add or update configuration setting {0} to value {1}. Ensure you have read/write access to path: {0}.
        /// </summary>
        internal static string UnableToAddUpdateConfigSetting {
            get {
                return ResourceManager.GetString("UnableToAddUpdateConfigSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize the printer using the printer settings supplied..
        /// </summary>
        internal static string UnableToInitializePrinterSettings {
            get {
                return ResourceManager.GetString("UnableToInitializePrinterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load application settings. Ensure you have read/write access to path: {0}.
        /// </summary>
        internal static string UnableToLoadSettings {
            get {
                return ResourceManager.GetString("UnableToLoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DocumentContract object supplied is not supported..
        /// </summary>
        internal static string UnsupportedDocumentContract {
            get {
                return ResourceManager.GetString("UnsupportedDocumentContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TargetType property of the DocumentContract object is not supported..
        /// </summary>
        internal static string UnsupportedTargetType {
            get {
                return ResourceManager.GetString("UnsupportedTargetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the status task to {0}{1}..
        /// </summary>
        internal static string UpdatingStatusMessage {
            get {
                return ResourceManager.GetString("UpdatingStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML declaration is not found..
        /// </summary>
        internal static string XmlDeclarationNotFound {
            get {
                return ResourceManager.GetString("XmlDeclarationNotFound", resourceCulture);
            }
        }
    }
}
